### ISSUE TITLE
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 14 path $

### ISSUE THREAD

**Issue by phramusca** [yvasyliev/deezer-api#18]
Hi,

I tried your wrapper but I can cannot login. During this line :

`AccessToken accessToken = deezerApi.auth().getAccessToken(APP_ID, SECRET, code).execute();`

I am getting an exception after having entered  my code:

`Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 14 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:1135)
	at com.google.gson.Gson.fromJson(Gson.java:1125)
	at com.google.gson.Gson.fromJson(Gson.java:1034)
	at com.google.gson.Gson.fromJson(Gson.java:969)
	at api.deezer.converters.PojoConverter.convert(PojoConverter.java:27)
	at api.deezer.converters.PojoConverter.convert(PojoConverter.java:10)
	at api.deezer.validators.DeezerResponseValidator.hasErrorField(DeezerResponseValidator.java:33)
	at api.deezer.validators.DeezerResponseValidator.test(DeezerResponseValidator.java:25)
	at api.deezer.validators.DeezerResponseValidator.test(DeezerResponseValidator.java:12)
	at api.deezer.http.impl.DeezerRequest.execute(DeezerRequest.java:65)
	at com.mycompany.mavenproject1.DeezerApp.main(DeezerApp.java:52)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 14 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:1131)
	... 10 more`

Any idea what can be wrong ?

**Comment by yvasyliev** [comment]
Hi @phramusca, 

Please check that `REDIRECT_URI` must be the same as `Application domain` on https://developers.deezer.com/myapps.

Also you can enable `DEBUG` logging level (`SLF4J` implementation) to find which JSON is not parsable...

**Comment by yvasyliev** [comment]
@phramusca, to enable logging you need to perform these steps:
1. Add to your `pom.xml`:
```xml
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-slf4j2-impl</artifactId>
    <version>2.19.0</version>
</dependency>
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.19.0</version>
</dependency>
```
2. Create a `log4j2.xml` file inside `resources` folder with the following content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <Appenders>
        <Console name="stdout" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>
    </Appenders>
    <Loggers>
        <Root level="ALL">
            <AppenderRef ref="stdout"/>
        </Root>
    </Loggers>
</Configuration>
```
3. Run your application and check console output

**Comment by phramusca** [comment]
Thanks. Here is the result. I only replaced sensitive data by xxxxxxxxxxxxxxxxxxxxxxxxxxxx

20:25:14.642 [main] DEBUG api.deezer.http.impl.DefaultHttpClient - Request: method=GET, url=https://connect.deezer.com/oauth/access_token.php, params={output=json, code=xxxxxxxxxxxxxxxxxxxxxxxxxxxx, secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxx, request_method=get, app_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxx}
20:25:15.121 [main] DEBUG api.deezer.http.impl.DefaultHttpClient - Response: status=200, body=access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&expires=3481
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 14 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:1135)
	at com.google.gson.Gson.fromJson(Gson.java:1125)
	at com.google.gson.Gson.fromJson(Gson.java:1034)
	at com.google.gson.Gson.fromJson(Gson.java:969)
	at api.deezer.converters.PojoConverter.convert(PojoConverter.java:27)
	at api.deezer.converters.PojoConverter.convert(PojoConverter.java:10)
	at api.deezer.validators.DeezerResponseValidator.hasErrorField(DeezerResponseValidator.java:33)
	at api.deezer.validators.DeezerResponseValidator.test(DeezerResponseValidator.java:25)
	at api.deezer.validators.DeezerResponseValidator.test(DeezerResponseValidator.java:12)
	at api.deezer.http.impl.DeezerRequest.execute(DeezerRequest.java:65)
	at com.mycompany.mavenproject1.DeezerApp.main(DeezerApp.java:52)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 14 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:1131)
	... 10 more

**Comment by yvasyliev** [comment]
@phramusca , please update to version `1.1.4` and check

**Comment by phramusca** [comment]
It works like a charm now. Thanks for the quick fix ! 

----- Mail original -----

De: "Yevhen Vasyliev" ***@***.***> 
À: "yvasyliev/deezer-api" ***@***.***> 
Cc: "phramusca" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 1 Décembre 2022 16:13:57 
Objet: Re: [yvasyliev/deezer-api] com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 14 path $ (Issue #18) 



@phramusca , please update to version 1.1.4 and check
